import React, { createContext, useContext, useState, useCallback, useEffect, useRef } from 'react';
import { useLocation } from 'react-router-dom';
import { useCustomerStore } from '@/stores/customerStore';
import { useOrganizationStore } from '@/stores/organizationStore';
import { useAuthStore } from '@/stores/authStore';
import { supabase } from '@/lib/supabase';
import toast from 'react-hot-toast';
import type { ActionProposal, ActionStatus, ActionResult, ChoiceOption, ChoicesConfig } from '@/types/copilot-actions.types';
import { parseActionProposal } from '@/utils/parseActionProposal';
import { executeAction, checkActionPermission } from '@/utils/executeAction';
import { getAuthToken } from '@/utils/auth.utils';
import { useImpersonationStore } from '@/stores/impersonationStore';
import { buildPersonalizationQuestions, buildPersonalizationSummaryMessage, type PersonalizationQuestion } from '@/config/personalization-questions.config';
import { logQBEvent } from '@/utils/qbActionLog';
import { useCopilotChatStore } from '@/stores/copilotChatStore';
import { messageToRow, rowToMessage } from '@/utils/copilotMessageMapper';

export interface Message {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
  action?: ActionProposal;
  actionStatus?: ActionStatus;
  actionResult?: ActionResult;
  choices?: ChoiceOption[];
  choiceSelected?: string;
  choicesConfig?: ChoicesConfig;
  choicesSelected?: string[];
  otherText?: string;
  feedbackRating?: 'positive' | 'negative';
  /** Stored when disambiguation is needed -- the action waiting for customer selection */
  pendingAction?: ActionProposal;
  /** True for ephemeral acknowledgment messages (no feedback buttons) */
  isAcknowledgment?: boolean;
  /** True when choices were generated by AI (CHOICE_PROPOSAL), not deterministic quarterback choices */
  isAIGeneratedChoices?: boolean;
}

interface ContextData {
  page?: string;
  data?: any;
}

interface CoPilotConfig {
  provider: 'internal' | 'openai' | 'anthropic' | 'ollama' | 'custom';
  apiKey?: string;
  model?: string;
  endpoint?: string;
}

interface TokenUsage {
  tokensUsed: number;
  tokensRemaining: number;
  tokensAllocated: number;
}

interface CoPilotContextType {
  isOpen: boolean;
  panelSide: 'left' | 'right';
  messages: Message[];
  isLoading: boolean;
  currentContext: ContextData | null;
  config: CoPilotConfig;
  tokenUsage: TokenUsage | null;
  openPanel: () => void;
  closePanel: () => void;
  setPanelSide: (side: 'left' | 'right') => void;
  sendMessage: (content: string) => Promise<void>;
  clearMessages: () => void;
  setContext: (context: ContextData) => void;
  setConfig: (config: CoPilotConfig) => void;
  confirmAction: (messageId: string, editedFields: Record<string, any>) => Promise<void>;
  cancelAction: (messageId: string) => void;
  addAssistantMessage: (msg: Omit<Message, 'id' | 'timestamp'>) => void;
  markChoiceSelected: (messageId: string, choiceId: string) => void;
  markChoicesSelected: (messageId: string, selectedIds: string[], otherText?: string) => void;
  setMessageFeedback: (messageId: string, rating: 'positive' | 'negative') => void;
  // Personalization interview
  startPersonalizationInterview: (industry: string, businessName: string, agentName: string, currentValues: Record<string, string>) => void;
  advancePersonalization: (answerText: string, hasOtherText?: boolean) => void;
  isPersonalizationInterview: boolean;
  pAcknowledgmentLoading: boolean;
  // Persistent conversation management
  activeConversationId: string | null;
  conversationCustomerId: string | null;
  startNewConversation: () => void;
  loadConversation: (conversationId: string) => Promise<void>;
  setConversationCustomerId: (customerId: string | null) => void;
}

const CoPilotContext = createContext<CoPilotContextType | undefined>(undefined);

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://zkpfzrbbupgiqkzqydji.supabase.co';

export const CoPilotProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [isOpen, setIsOpen] = useState(false);
  const [panelSide, setPanelSide] = useState<'left' | 'right'>('right');
  const [messages, setMessages] = useState<Message[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [currentContext, setCurrentContext] = useState<ContextData | null>(null);
  const [tokenUsage, setTokenUsage] = useState<TokenUsage | null>(null);
  const [config, setConfig] = useState<CoPilotConfig>({
    provider: 'internal',
    model: 'internal-assistant',
  });

  // Location for auto-linking customer context
  const location = useLocation();

  // Persistent conversation state
  const [activeConversationId, setActiveConversationId] = useState<string | null>(null);
  const [conversationCustomerId, setConversationCustomerIdState] = useState<string | null>(null);
  const savedMessageIdsRef = useRef<Set<string>>(new Set());

  // Auto-link customer context from URL when on a customer profile page
  // This runs on route change so new conversations auto-inherit the customer ID
  const prevAutoLinkedCustomerRef = useRef<string | null>(null);
  useEffect(() => {
    const match = location.pathname.match(/^\/dashboard\/customers\/([a-f0-9-]{36})$/i);
    const urlCustomerId = match ? match[1] : null;

    if (urlCustomerId && urlCustomerId !== prevAutoLinkedCustomerRef.current) {
      // Navigated to a customer page -- auto-link if not already linked to a different customer
      if (!conversationCustomerId || !activeConversationId) {
        setConversationCustomerIdState(urlCustomerId);
      }
      prevAutoLinkedCustomerRef.current = urlCustomerId;
    } else if (!urlCustomerId && prevAutoLinkedCustomerRef.current) {
      // Navigated away from customer page -- only clear auto-link if no active conversation
      // (to avoid clearing a manually linked customer)
      if (!activeConversationId) {
        setConversationCustomerIdState(null);
      }
      prevAutoLinkedCustomerRef.current = null;
    }
  }, [location.pathname, activeConversationId, conversationCustomerId]);

  // Personalization interview state
  const [pQuestions, setPQuestions] = useState<PersonalizationQuestion[]>([]);
  const [pIndex, setPIndex] = useState(0);
  const [pAnswers, setPAnswers] = useState<Record<string, string>>({});
  const [pIndustry, setPIndustry] = useState('general_business');
  const [pAcknowledgmentLoading, setPAcknowledgmentLoading] = useState(false);
  const [pSiteContext, setPSiteContext] = useState('');
  const isPersonalizationInterview = pQuestions.length > 0 && pIndex < pQuestions.length;

  // Clear CoPilot conversation when the impersonation target changes
  // (e.g., switching from Alex -> Josie, or starting/ending impersonation)
  const { isImpersonating, targetUserId } = useImpersonationStore();
  const prevTargetRef = useRef<string | null>(null);

  useEffect(() => {
    const key = isImpersonating ? targetUserId : '__self__';
    if (prevTargetRef.current !== null && prevTargetRef.current !== key) {
      setMessages([]);
      setTokenUsage(null);
      setActiveConversationId(null);
      savedMessageIdsRef.current.clear();
    }
    prevTargetRef.current = key;
  }, [isImpersonating, targetUserId]);

  const openPanel = useCallback(() => {
    setIsOpen(true);
  }, []);

  const closePanel = useCallback(() => {
    setIsOpen(false);
  }, []);

  const clearMessages = useCallback(() => {
    setMessages([]);
    setActiveConversationId(null);
    savedMessageIdsRef.current.clear();
  }, []);

  const addAssistantMessage = useCallback((msg: Omit<Message, 'id' | 'timestamp'>) => {
    const message: Message = {
      ...msg,
      id: Date.now().toString(),
      timestamp: new Date(),
    };
    setMessages(prev => [...prev, message]);
  }, []);

  const markChoiceSelected = useCallback((messageId: string, choiceId: string) => {
    setMessages(prev => prev.map(m =>
      m.id === messageId ? { ...m, choiceSelected: choiceId } : m
    ));
  }, []);

  const markChoicesSelected = useCallback((messageId: string, selectedIds: string[], otherText?: string) => {
    setMessages(prev => prev.map(m =>
      m.id === messageId ? { ...m, choicesSelected: selectedIds, otherText: otherText || undefined } : m
    ));
  }, []);

  const setMessageFeedback = useCallback((messageId: string, rating: 'positive' | 'negative') => {
    setMessages(prev => prev.map(m =>
      m.id === messageId ? { ...m, feedbackRating: rating } : m
    ));
  }, []);

  const setContext = useCallback((context: ContextData) => {
    setCurrentContext(context);
  }, []);

  const { customers, addNote, fetchCustomers } = useCustomerStore();

  // Confirm an action proposed by the AI
  const confirmAction = useCallback(async (messageId: string, editedFields: Record<string, any>) => {
    // Set status to executing
    setMessages(prev => prev.map(m =>
      m.id === messageId ? { ...m, actionStatus: 'executing' as ActionStatus } : m
    ));

    const message = messages.find(m => m.id === messageId);
    if (!message?.action) return;

    const result = await executeAction(message.action, editedFields);

    // Update the message with the result
    setMessages(prev => prev.map(m =>
      m.id === messageId
        ? { ...m, actionStatus: (result.success ? 'completed' : 'failed') as ActionStatus, actionResult: result }
        : m
    ));

    // Log QB action result if in quarterback mode
    if (currentContext?.data?.quarterbackMode) {
      const insightData = currentContext.data.insightData;
      logQBEvent({
        insightId: insightData?.id || '',
        insightType: currentContext.data.insightType || '',
        eventType: result.success ? 'action_completed' : 'action_failed',
        actionType: message.action.actionType,
        actionResult: result.success ? 'completed' : 'failed',
        customerId: insightData?.customer_id,
        customerName: insightData?.customer_name,
        dealValue: insightData?.value || insightData?.total_amount || insightData?.amount_outstanding,
      });
    }

    if (result.success) {
      toast.success(result.message);
    } else {
      toast.error(result.message);
    }
  }, [messages, currentContext]);

  // Cancel an action proposed by the AI
  const cancelAction = useCallback((messageId: string) => {
    setMessages(prev => prev.map(m =>
      m.id === messageId ? { ...m, actionStatus: 'cancelled' as ActionStatus } : m
    ));
  }, []);

  const sendMessage = useCallback(async (content: string) => {
    const userMessage: Message = {
      id: Date.now().toString(),
      role: 'user',
      content,
      timestamp: new Date(),
    };

    setMessages(prev => [...prev, userMessage]);
    setIsLoading(true);

    try {
      const lowerContent = content.toLowerCase();

      // LOCAL ACTIONS: Note adding (handled locally, no AI needed)
      if (lowerContent.includes('add a note') || lowerContent.includes('add note') || lowerContent.includes('put a note') || lowerContent.includes('create a note')) {
        if (customers.length === 0) {
          await fetchCustomers();
        }

        let customer = null;
        for (const c of useCustomerStore.getState().customers) {
          if (content.toLowerCase().includes(c.name.toLowerCase())) {
            customer = c;
            break;
          }
        }

        if (customer) {
          let noteContent = "";
          if (content.includes("that ")) {
            noteContent = content.split("that ").slice(1).join("that ").trim();
          } else if (content.includes("note ")) {
            noteContent = content.split("note ").slice(1).join("note ").trim();
          } else {
            noteContent = "Update from CoPilot";
          }

          if (noteContent) {
            await addNote({
              customer_id: customer.id,
              content: noteContent
            });

            const assistantMessage: Message = {
              id: (Date.now() + 1).toString(),
              role: 'assistant',
              content: `✅ Done! I've added that note to **${customer.name}'s** profile.\n\n**Note:** "${noteContent}"`,
              timestamp: new Date(),
            };
            setMessages(prev => [...prev, assistantMessage]);
            toast.success('Note added successfully');
            return;
          }
        } else {
          const assistantMessage: Message = {
            id: (Date.now() + 1).toString(),
            role: 'assistant',
            content: "I couldn't find a customer matching that name in your CRM. Could you please double-check the name or navigate to their profile so I can help?",
            timestamp: new Date(),
          };
          setMessages(prev => [...prev, assistantMessage]);
          return;
        }
      }

      // AI RESPONSE: Call the Edge Function
      // Use shared auth utility to avoid Supabase AbortController issue
      const accessToken = await getAuthToken();

      if (!accessToken) {
        const assistantMessage: Message = {
          id: (Date.now() + 1).toString(),
          role: 'assistant',
          content: "I need you to be signed in to use AI features. Please refresh the page and try again.",
          timestamp: new Date(),
        };
        setMessages(prev => [...prev, assistantMessage]);
        return;
      }

      const conversationHistory = messages.slice(-10).map(m => ({
        role: m.role as 'user' | 'assistant',
        content: m.content,
      }));

      const org = useOrganizationStore.getState().currentOrganization;
      const membership = useOrganizationStore.getState().currentMembership;

      // Read AI CoPilot Context — use impersonated user's profile when active
      const impersonation = useImpersonationStore.getState();
      const profile = useAuthStore.getState().profile;

      const effectiveMeta = impersonation.isImpersonating && impersonation.targetProfile
        ? (impersonation.targetProfile.profile_metadata || {})
        : (profile?.profile_metadata || {});
      const effectiveName = impersonation.isImpersonating
        ? (impersonation.targetUserName || '')
        : (profile?.full_name || '');

      const userPreferences = {
        full_name: effectiveName,
        work_style: effectiveMeta.work_style || [],
        communication_preference: effectiveMeta.communication_preference || [],
        goals: effectiveMeta.goals || [],
        expertise: effectiveMeta.expertise || [],
        interests: effectiveMeta.interests || [],
      };
      const hasAIContext = !!(
        effectiveMeta.work_style?.length ||
        effectiveMeta.communication_preference?.length ||
        effectiveMeta.goals?.length
      );

      const isAdminPage = currentContext?.page?.startsWith('Admin') ||
        window.location.pathname.startsWith('/admin');

      const response = await fetch(`${SUPABASE_URL}/functions/v1/copilot-chat`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${accessToken}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          message: content,
          conversationHistory,
          userPreferences,
          hasUserProfile: hasAIContext,
          // Pass impersonation context so edge function uses correct user for tokens + data
          ...(impersonation.isImpersonating && impersonation.targetUserId && {
            impersonation: {
              targetUserId: impersonation.targetUserId,
              targetOrgId: impersonation.targetOrgId,
            },
          }),
          context: {
            page: currentContext?.page || 'Dashboard',
            industry: org?.industry_template || 'general_business',
            orgName: org?.name || 'Your Organization',
            userRole: membership?.role || 'user',
            ...(isAdminPage && { isAdmin: true }),
            // AI Quarterback mode: forward insight data for hyper business-savvy responses
            ...(currentContext?.data?.quarterbackMode && {
              quarterbackMode: true,
              insightType: currentContext.data.insightType,
              insightData: currentContext.data.insightData,
            }),
            // Voice agent personalization mode
            ...(currentContext?.data?.personalizationMode && {
              personalizationMode: true,
              personalizationData: {
                currentValues: currentContext.data.currentValues,
                agentName: currentContext.data.agentName,
                businessName: currentContext.data.businessName,
              },
            }),
          },
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        const status = response.status;
        const errorCode = data.error || '';
        console.error('[CoPilot] API error', { status, error: errorCode, debug: data.debug });

        let errorContent: string;

        if (errorCode === 'token_limit_reached') {
          setTokenUsage({
            tokensUsed: data.tokensUsed || 0,
            tokensRemaining: 0,
            tokensAllocated: data.tokensAllocated || 0,
          });
          errorContent = "🚫 **Out of AI tokens**\n\nYou've used all your AI tokens for this month. To continue using CoPilot AI:\n\n• **Upgrade your plan** for more monthly tokens\n• Tokens reset at the start of each billing period\n\nI can still help with basic CRM actions like adding notes!";
        } else if (status === 401) {
          errorContent = "Your session has expired. Please refresh the page to sign in again.";
        } else if (status === 403) {
          errorContent = "I couldn't find your organization. Please make sure you're signed into a valid account.";
        } else if (status === 429) {
          errorContent = "The AI service is currently rate-limited. Please wait a moment and try again.";
        } else {
          errorContent = `I encountered an issue (error ${status}). Please try again in a moment.`;
        }

        const assistantMessage: Message = {
          id: (Date.now() + 1).toString(),
          role: 'assistant',
          content: errorContent,
          timestamp: new Date(),
        };
        setMessages(prev => [...prev, assistantMessage]);
        return;
      }

      // Update token usage
      if (data.tokensRemaining !== undefined) {
        setTokenUsage({
          tokensUsed: data.tokensUsed || 0,
          tokensRemaining: data.tokensRemaining,
          tokensAllocated: data.tokensAllocated || 0,
        });
      }

      // Parse the AI response for action proposals
      const parsed = parseActionProposal(data.response);

      // Enrich action proposals with local CRM data (phone, email, customer_id)
      // If multiple customers share the same name, show disambiguation choices
      let disambiguationChoices: import('@/types/copilot-actions.types').ChoiceOption[] | null = null;
      let disambiguationAction: ActionProposal | undefined;

      if (parsed.action) {
        const customerNameField = parsed.action.fields.find(f => f.key === 'customer_name');
        if (customerNameField?.value) {
          const store = useCustomerStore.getState();
          if (store.customers.length === 0) {
            await store.fetchCustomers();
          }
          const allCustomers = useCustomerStore.getState().customers;
          const searchName = customerNameField.value.toLowerCase().trim();

          // Collect ALL matches at each tier, stop at the first tier that has results
          let matches: typeof allCustomers = [];
          const exactMatches = allCustomers.filter(c => c.name?.toLowerCase() === searchName);
          if (exactMatches.length > 0) {
            matches = exactMatches;
          } else {
            const partialMatches = allCustomers.filter(c => c.name?.toLowerCase().includes(searchName));
            if (partialMatches.length > 0) {
              matches = partialMatches;
            } else {
              const parts = searchName.split(/\s+/);
              if (parts.length >= 2) {
                matches = allCustomers.filter(c => {
                  const name = c.name?.toLowerCase() || '';
                  return parts.every(p => name.includes(p));
                });
              }
            }
          }

          // Deduplicate by ID
          const uniqueMatches = [...new Map(matches.map(c => [c.id, c])).values()];

          if (uniqueMatches.length === 1) {
            // Single match -- auto-fill fields
            const match = uniqueMatches[0];
            const phoneField = parsed.action.fields.find(f => f.key === 'to_phone');
            if (phoneField && !phoneField.value && match.phone) {
              phoneField.value = match.phone;
            }
            const emailField = parsed.action.fields.find(f => f.key === 'to_email');
            if (emailField && !emailField.value && match.email) {
              emailField.value = match.email;
            }
            const idField = parsed.action.fields.find(f => f.key === 'customer_id');
            if (idField && !idField.value) {
              idField.value = match.id;
            }
          } else if (uniqueMatches.length > 1) {
            // Multiple matches -- ask user to disambiguate
            disambiguationAction = parsed.action;
            parsed.action = undefined as any; // Strip action so ActionCard doesn't render yet
            disambiguationChoices = uniqueMatches.slice(0, 4).map(c => {
              const details: string[] = [];
              if (c.phone) details.push(c.phone);
              if (c.email) details.push(c.email);
              if (c.company) details.push(c.company);
              return {
                id: c.id,
                label: c.name || 'Unknown',
                description: details.join(' · ') || 'No contact info',
                icon: 'User',
              };
            });
          }
        }
      }

      // Permission gate: strip action if user doesn't have permission
      let actionToShow = parsed.action;
      let displayContent = parsed.textContent;
      if (actionToShow && !checkActionPermission(actionToShow.actionType)) {
        actionToShow = undefined;
        displayContent += "\n\n⚠️ You don't have permission to perform this action. Contact your admin.";
      }

      // If disambiguation is needed, show choices instead of the action card
      if (disambiguationChoices && disambiguationAction) {
        const disambigMessage: Message = {
          id: (Date.now() + 1).toString(),
          role: 'assistant',
          content: displayContent + `\n\nI found **${disambiguationChoices.length} customers** matching that name. Which one did you mean?`,
          timestamp: new Date(),
          choices: disambiguationChoices,
          pendingAction: disambiguationAction,
        };
        setMessages(prev => [...prev, disambigMessage]);
      } else {
        const assistantMessage: Message = {
          id: (Date.now() + 1).toString(),
          role: 'assistant',
          content: displayContent,
          timestamp: new Date(),
          action: actionToShow || undefined,
          actionStatus: actionToShow ? 'proposed' : undefined,
          choicesConfig: parsed.choicesConfig || undefined,
          choices: parsed.followUpChoices || undefined,
          isAIGeneratedChoices: !!parsed.followUpChoices,
        };
        setMessages(prev => [...prev, assistantMessage]);
      }

    } catch (error) {
      console.error('[CoPilot] Unexpected error', error);

      let errorContent: string;

      if (error instanceof TypeError && String(error.message).includes('fetch')) {
        errorContent = "Couldn't reach the AI service. Please check your internet connection and try again.";
      } else if (error instanceof DOMException && error.name === 'AbortError') {
        errorContent = "The request was cancelled. Please try again.";
      } else {
        errorContent = "Something unexpected went wrong. Please check your connection and try again.";
      }

      const errorMessage: Message = {
        id: (Date.now() + 1).toString(),
        role: 'assistant',
        content: errorContent,
        timestamp: new Date(),
      };
      setMessages(prev => [...prev, errorMessage]);
    } finally {
      setIsLoading(false);
    }
  }, [customers, addNote, fetchCustomers, messages, currentContext]);

  // --- Personalization Interview Methods (must be after sendMessage) ---
  const injectPersonalizationQuestion = useCallback((questions: PersonalizationQuestion[], index: number) => {
    const q = questions[index];
    if (!q) return;
    const msg: Message = {
      id: Date.now().toString(),
      timestamp: new Date(),
      role: 'assistant',
      content: q.text,
      choicesConfig: q.choicesConfig,
    };
    setMessages(prev => [...prev, msg]);
  }, []);

  const startPersonalizationInterview = useCallback((
    industry: string,
    businessName: string,
    agentName: string,
    currentValues: Record<string, string>
  ) => {
    const questions = buildPersonalizationQuestions(industry, businessName, agentName, currentValues);
    setPQuestions(questions);
    setPIndex(0);
    setPAnswers({});
    setPIndustry(industry);
    setPSiteContext('');
    setMessages([]);
    // Inject the first question after a brief delay so the panel is visible
    setTimeout(() => injectPersonalizationQuestion(questions, 0), 150);
  }, [injectPersonalizationQuestion]);

  // Inject an acknowledgment bubble (no feedback buttons, no choices)
  const injectAcknowledgmentMessage = useCallback((text: string) => {
    const msg: Message = {
      id: Date.now().toString(),
      timestamp: new Date(),
      role: 'assistant',
      content: text,
      isAcknowledgment: true,
    };
    setMessages(prev => [...prev, msg]);
  }, []);

  // Call the edge function in acknowledgmentMode for AI-generated acknowledgments.
  // Supports accumulated context, next-question merging, site context caching,
  // and adaptive options generation for isAdaptive questions.
  const generateAIAcknowledgment = useCallback(async (
    answerText: string,
    questionText: string,
    accumulatedAnswers?: Record<string, string>,
    nextQuestionText?: string,
    cachedSiteContext?: string,
    nextQuestionFieldKey?: string | null,
    isNextQuestionAdaptive?: boolean,
    nextQuestionDefaultOptions?: Array<{ id: string; label: string; description: string; icon: string }> | null,
  ): Promise<{ text: string; siteContext?: string; adaptedChoicesConfig?: import('@/types/copilot-actions.types').ChoicesConfig }> => {
    try {
      const accessToken = await getAuthToken();
      if (!accessToken) return { text: 'Got it, thanks!' };

      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 12000); // Extended for adaptive calls

      const org = useOrganizationStore.getState().currentOrganization;
      const impersonation = useImpersonationStore.getState();

      const response = await fetch(`${SUPABASE_URL}/functions/v1/copilot-chat`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${accessToken}`,
          'Content-Type': 'application/json',
        },
        signal: controller.signal,
        body: JSON.stringify({
          message: answerText,
          acknowledgmentMode: true,
          acknowledgmentContext: {
            questionText,
            accumulatedAnswers: accumulatedAnswers || {},
            nextQuestionText: nextQuestionText || null,
            cachedSiteContext: cachedSiteContext || null,
            nextQuestionFieldKey: nextQuestionFieldKey || null,
            isNextQuestionAdaptive: isNextQuestionAdaptive || false,
            nextQuestionDefaultOptions: isNextQuestionAdaptive ? (nextQuestionDefaultOptions || null) : null,
          },
          ...(impersonation.isImpersonating && impersonation.targetUserId && {
            impersonation: {
              targetUserId: impersonation.targetUserId,
              targetOrgId: impersonation.targetOrgId,
            },
          }),
          context: {
            industry: org?.industry_template || 'general_business',
            orgName: org?.name || 'Your Organization',
          },
        }),
      });

      clearTimeout(timeout);

      if (!response.ok) return { text: 'Got it, thanks!' };

      const data = await response.json();

      // Update token usage from response
      if (data.tokensRemaining !== undefined) {
        setTokenUsage({
          tokensUsed: data.tokensUsed || 0,
          tokensRemaining: data.tokensRemaining,
          tokensAllocated: data.tokensAllocated || 0,
        });
      }

      return {
        text: data.response || 'Got it, thanks!',
        siteContext: data.siteContext || undefined,
        adaptedChoicesConfig: data.adaptedChoicesConfig || undefined,
      };
    } catch {
      return { text: 'Got it, thanks!' };
    }
  }, []);

  const advancePersonalization = useCallback(async (answerText: string, hasOtherText?: boolean) => {
    const currentQ = pQuestions[pIndex];
    if (!currentQ) return;

    // Store answer
    const newAnswers = { ...pAnswers, [currentQ.fieldKey]: answerText };
    setPAnswers(newAnswers);

    const nextIndex = pIndex + 1;
    setPIndex(nextIndex);
    const nextQ = nextIndex < pQuestions.length ? pQuestions[nextIndex] : null;

    if (hasOtherText) {
      // --- AI acknowledgment path (freeform text present) ---
      setPAcknowledgmentLoading(true);
      try {
        const result = await generateAIAcknowledgment(
          answerText,
          currentQ.text,
          newAnswers,
          nextQ?.text || undefined,
          pSiteContext || undefined,
          nextQ?.fieldKey || null,
          nextQ?.isAdaptive || false,
          nextQ?.isAdaptive ? nextQ.choicesConfig.options : null,
        );

        // Cache site context for subsequent questions (scrape once, reuse)
        if (result.siteContext) {
          setPSiteContext(result.siteContext);
        }

        if (nextQ) {
          // Use adapted options if the edge function returned them, otherwise use static defaults
          const resolvedChoicesConfig = result.adaptedChoicesConfig
            ? { ...nextQ.choicesConfig, options: result.adaptedChoicesConfig.options }
            : nextQ.choicesConfig;

          // MERGED message: AI ack + transition text with next question's choice cards attached
          const mergedMsg: Message = {
            id: Date.now().toString(),
            timestamp: new Date(),
            role: 'assistant',
            content: result.text,
            isAcknowledgment: true,
            choicesConfig: resolvedChoicesConfig,
          };
          setMessages(prev => [...prev, mergedMsg]);
        } else {
          // Last question: inject ack only, then finalize
          injectAcknowledgmentMessage(result.text);
          setPQuestions([]);
          const summaryMsg = buildPersonalizationSummaryMessage(newAnswers, pIndustry);
          setTimeout(() => { sendMessage(summaryMsg); }, 700);
        }
      } finally {
        setPAcknowledgmentLoading(false);
      }
    } else {
      // --- Template acknowledgment path (predefined selections only, zero tokens) ---
      const ackText = (currentQ.acknowledgmentTemplate || 'Got it!').replace('{answer}', answerText);
      injectAcknowledgmentMessage(ackText);

      if (nextQ) {
        setTimeout(() => injectPersonalizationQuestion(pQuestions, nextIndex), 700);
      } else {
        setPQuestions([]);
        const summaryMsg = buildPersonalizationSummaryMessage(newAnswers, pIndustry);
        setTimeout(() => { sendMessage(summaryMsg); }, 700);
      }
    }
  }, [pQuestions, pIndex, pAnswers, pIndustry, pSiteContext, injectPersonalizationQuestion, sendMessage, generateAIAcknowledgment, injectAcknowledgmentMessage]);

  // --- Persistent Conversation Methods ---

  const setConversationCustomerId = useCallback((customerId: string | null) => {
    setConversationCustomerIdState(customerId);
  }, []);

  const startNewConversation = useCallback(() => {
    setMessages([]);
    setActiveConversationId(null);
    savedMessageIdsRef.current.clear();
  }, []);

  const loadConversation = useCallback(async (conversationId: string) => {
    const store = useCopilotChatStore.getState();
    const rows = await store.loadMessages(conversationId);
    const loaded = rows.map(rowToMessage);
    setMessages(loaded);
    setActiveConversationId(conversationId);
    savedMessageIdsRef.current = new Set(loaded.map(m => m.id));

    // Set customer link from loaded conversation
    const conv = store.conversations.find(c => c.id === conversationId);
    if (conv?.customer_id) {
      setConversationCustomerIdState(conv.customer_id);
    }
  }, []);

  // Auto-persist messages to database (fire-and-forget)
  const prevMessagesLengthRef = useRef(0);
  useEffect(() => {
    // Skip during personalization interviews (ephemeral by design)
    if (isPersonalizationInterview) {
      prevMessagesLengthRef.current = messages.length;
      return;
    }

    if (messages.length <= prevMessagesLengthRef.current) {
      prevMessagesLengthRef.current = messages.length;
      return;
    }

    const newMessages = messages.slice(prevMessagesLengthRef.current);
    prevMessagesLengthRef.current = messages.length;

    // Fire-and-forget persistence
    (async () => {
      const store = useCopilotChatStore.getState();
      let convId = activeConversationId;

      // Auto-create conversation on first message
      if (!convId && newMessages.length > 0) {
        const firstUserMsg = newMessages.find(m => m.role === 'user');
        const contextType = currentContext?.data?.quarterbackMode ? 'quarterback' as const
          : conversationCustomerId ? 'customer' as const
          : 'general' as const;

        convId = await store.createConversation({
          customerId: conversationCustomerId,
          contextType,
          title: firstUserMsg ? store.generateTitle(firstUserMsg.content) : 'New Conversation',
        });

        if (convId) {
          setActiveConversationId(convId);
        }
      }

      if (!convId) return;

      // Save each new message that hasn't been saved yet
      for (const msg of newMessages) {
        if (savedMessageIdsRef.current.has(msg.id)) continue;
        savedMessageIdsRef.current.add(msg.id);
        const row = messageToRow(msg, convId);
        await store.saveMessage(row);
      }
    })();
  }, [messages.length, activeConversationId, isPersonalizationInterview, conversationCustomerId, currentContext]);

  // Persist feedback and action status updates
  const persistMessageUpdate = useCallback(async (messageId: string, updates: Record<string, any>) => {
    if (!activeConversationId || !savedMessageIdsRef.current.has(messageId)) return;
    // Find the DB message ID -- our in-memory IDs are Date.now() strings, but saved ones use UUID
    // Since we save in order, we can find by matching content
    // For simplicity, do a fire-and-forget update by the in-memory ID stored in metadata
    const store = useCopilotChatStore.getState();
    await store.updateMessage(messageId, updates);
  }, [activeConversationId]);

  return (
    <CoPilotContext.Provider
      value={{
        isOpen,
        panelSide,
        messages,
        isLoading,
        currentContext,
        config,
        tokenUsage,
        openPanel,
        closePanel,
        setPanelSide,
        sendMessage,
        clearMessages,
        setContext,
        setConfig,
        confirmAction,
        cancelAction,
        addAssistantMessage,
        markChoiceSelected,
        markChoicesSelected,
        setMessageFeedback,
        startPersonalizationInterview,
        advancePersonalization,
        isPersonalizationInterview,
        pAcknowledgmentLoading,
        activeConversationId,
        conversationCustomerId,
        startNewConversation,
        loadConversation,
        setConversationCustomerId,
      }}
    >
      {children}
    </CoPilotContext.Provider>
  );
};

export const useCoPilot = () => {
  const context = useContext(CoPilotContext);
  if (!context) {
    throw new Error('useCoPilot must be used within CoPilotProvider');
  }
  return context;
};
