import type { Module } from '../types/app.types';

export const AVAILABLE_MODULES: Record<string, Module> = {
  dashboard: {
    id: 'dashboard',
    name: 'Dashboard',
    description: 'Overview and analytics',
    icon: 'LayoutGrid',
    route: '/dashboard',
    requiredPermissions: [],
    category: 'system',
  },
  crm: {
    id: 'crm',
    name: 'CRM',
    description: 'Customer relationship management',
    icon: 'Users',
    route: '/customers',
    requiredPermissions: ['customers.read'],
    category: 'sales',
  },
  calendar: {
    id: 'calendar',
    name: 'Calendar',
    description: 'Appointments and scheduling',
    icon: 'Calendar',
    route: '/calendar',
    requiredPermissions: ['calendar.read'],
    category: 'operations',
  },
  quotes: {
    id: 'quotes',
    name: 'Quotes',
    description: 'Quote generation and management',
    icon: 'FileText',
    route: '/quotes',
    requiredPermissions: ['quotes.read'],
    dependencies: ['crm'],
    category: 'sales',
  },
  invoices: {
    id: 'invoices',
    name: 'Invoices',
    description: 'Invoice creation and tracking',
    icon: 'Receipt',
    route: '/invoices',
    requiredPermissions: ['invoices.read'],
    dependencies: ['crm'],
    category: 'finance',
  },
  products: {
    id: 'products',
    name: 'Products',
    description: 'Product catalog management',
    icon: 'Package',
    route: '/products',
    requiredPermissions: ['products.read'],
    category: 'operations',
  },
  inventory: {
    id: 'inventory',
    name: 'Inventory',
    description: 'Stock management',
    icon: 'Layers',
    route: '/inventory',
    requiredPermissions: ['inventory.read'],
    dependencies: ['products'],
    category: 'operations',
  },
  suppliers: {
    id: 'suppliers',
    name: 'Suppliers',
    description: 'Vendor management',
    icon: 'Building',
    route: '/suppliers',
    requiredPermissions: ['suppliers.read'],
    category: 'operations',
  },
  pipeline: {
    id: 'pipeline',
    name: 'Pipeline',
    description: 'Sales pipeline tracking',
    icon: 'BarChart3',
    route: '/pipeline',
    requiredPermissions: ['pipeline.read'],
    dependencies: ['crm'],
    category: 'sales',
  },
  calls: {
    id: 'calls',
    name: 'Calls',
    description: 'Call logging and tracking',
    icon: 'Phone',
    route: '/calls',
    requiredPermissions: ['calls.read'],
    category: 'operations',
  },
  tasks: {
    id: 'tasks',
    name: 'Tasks',
    description: 'Task management',
    icon: 'CheckSquare',
    route: '/tasks',
    requiredPermissions: ['tasks.read'],
    category: 'operations',
  },
  financials: {
    id: 'financials',
    name: 'Financials',
    description: 'Revenue and expense tracking',
    icon: 'DollarSign',
    route: '/financials',
    requiredPermissions: ['financials.read'],
    category: 'finance',
  },
};

export const INDUSTRY_TEMPLATES: Record<string, string[]> = {
  tax_accounting: ['dashboard', 'crm', 'calendar', 'invoices', 'financials', 'tasks', 'quotes'],
  distribution_logistics: ['dashboard', 'crm', 'products', 'inventory', 'suppliers', 'quotes', 'invoices', 'financials', 'pipeline'],
  gyms_fitness: ['dashboard', 'crm', 'calendar', 'invoices', 'tasks', 'calls', 'pipeline', 'products', 'inventory'],
  contractors_home_services: ['dashboard', 'crm', 'calendar', 'quotes', 'invoices', 'tasks', 'pipeline', 'calls'],
  healthcare: ['dashboard', 'crm', 'calendar', 'invoices', 'tasks', 'calls'],
  real_estate: ['dashboard', 'crm', 'calendar', 'pipeline', 'tasks', 'calls', 'quotes'],
  legal_services: ['dashboard', 'crm', 'calendar', 'invoices', 'tasks', 'pipeline', 'calls', 'quotes'],
  general_business: ['dashboard', 'crm', 'calendar', 'quotes', 'invoices', 'tasks', 'pipeline', 'calls'],
};

export const INDUSTRY_LABELS: Record<string, any> = {
  tax_accounting: {
    crm: { name: 'Clients' },
    quotes: { name: 'Engagement Letters' }
  },
  distribution_logistics: {
    crm: { name: 'Accounts' },
    pipeline: { name: 'Order Pipeline' }
  },
  gyms_fitness: {
    crm: { name: 'Members' },
    calendar: { name: 'Class Schedule' },
    pipeline: { name: 'Membership Pipeline' }
  },
  contractors_home_services: {
    crm: { name: 'Clients' },
    quotes: { name: 'Estimates' },
    pipeline: { name: 'Job Pipeline' }
  },
  healthcare: {
    crm: { name: 'Patients' },
    calendar: { name: 'Appointments' }
  },
  real_estate: {
    crm: { name: 'Contacts' },
    pipeline: { name: 'Deal Pipeline' },
    quotes: { name: 'Listing Proposals' }
  },
  legal_services: {
    crm: { name: 'Clients' },
    pipeline: { name: 'Case Pipeline' },
    quotes: { name: 'Fee Proposals' }
  },
};

export const PLAN_MODULE_ACCESS: Record<string, string[]> = {
  free: ['dashboard', 'crm', 'calendar', 'tasks', 'quotes', 'invoices'],
  business: ['dashboard', 'crm', 'calendar', 'tasks', 'quotes', 'invoices', 'calls', 'pipeline', 'products'],
  elite_premium: ['dashboard', 'crm', 'calendar', 'tasks', 'quotes', 'invoices', 'calls', 'pipeline', 'products', 'inventory', 'suppliers', 'financials'],
  enterprise: ['dashboard', 'crm', 'calendar', 'tasks', 'quotes', 'invoices', 'calls', 'pipeline', 'products', 'inventory', 'suppliers', 'financials'],
};

export const DEFAULT_PERMISSIONS: Record<string, string[]> = {
  owner: [
    'customers.read',
    'customers.write',
    'customers.delete',
    'calendar.read',
    'calendar.write',
    'quotes.read',
    'quotes.write',
    'invoices.read',
    'invoices.write',
    'products.read',
    'products.write',
    'pipeline.read',
    'pipeline.write',
    'calls.read',
    'calls.write',
    'tasks.read',
    'tasks.write',
    'financials.read',
    'settings.manage',
  ],
  admin: [
    'customers.read',
    'customers.write',
    'customers.delete',
    'calendar.read',
    'calendar.write',
    'quotes.read',
    'quotes.write',
    'invoices.read',
    'invoices.write',
    'products.read',
    'products.write',
    'pipeline.read',
    'pipeline.write',
    'calls.read',
    'calls.write',
    'tasks.read',
    'tasks.write',
    'financials.read',
  ],
  manager: [
    'customers.read',
    'customers.write',
    'calendar.read',
    'calendar.write',
    'quotes.read',
    'quotes.write',
    'invoices.read',
    'products.read',
    'pipeline.read',
    'pipeline.write',
    'calls.read',
    'calls.write',
    'tasks.read',
    'tasks.write',
  ],
  user: [
    'customers.read',
    'calendar.read',
    'calendar.write',
    'quotes.read',
    'invoices.read',
    'products.read',
    'pipeline.read',
    'calls.read',
    'tasks.read',
    'tasks.write',
  ],
};
